<?php

namespace CirTuSofiaBundle\Repository;

/**
 * RequestHallRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestHallRepository extends \Doctrine\ORM\EntityRepository
{

}
